Repository Shinhan-Hackathon-IJOAH/IJoah, pull requests merged in 2023-09, with the labels that each got.

#2 docs: backend 프로젝트 추가 (#1)
  backend/.gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/generated/com/shinhan/shbhack/ijoa/domain/QBaseEntity.java
  backend/src/main/generated/com/shinhan/shbhack/ijoa/domain/member/QMember.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/IjoaApplication.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/diary/DiaryController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/diary/requestdto/DiaryRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/MemberController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/requestdto/MemberRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/diary/command/DiaryService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/diary/query/DiaryQueryService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/command/MemberService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/query/MemberQueryService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/config/QueryDslConfig.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/config/SecurityConfig.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/file/FileExtensionFilter.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/file/FileStore.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/file/UploadFile.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/BaseEntity.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/entity/Comment.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/entity/Diary.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/entity/DiaryImage.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/entity/DiaryShare.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/repository/jpa/DiaryRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/repository/query/DiaryQueryRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Family.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Friend.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Member.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Mission.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Notification.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/ProfileImage.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/jpa/MemberRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/query/MemberQueryRepository.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/shinhan/shbhack/ijoa/IjoaApplicationTests.java
Labels: docs

#4 docs: merge 템플릿에 불필요한 부분 삭제
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#6 feat: merge 페이지 구조 설계
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/components/hi.txt
  frontend/src/index.css
  frontend/src/index.tsx
  frontend/src/logo.svg
  frontend/src/pages/ChildPage/ChildDiaryPage/ChildDiaryPage.tsx
  frontend/src/pages/ChildPage/ChildMainPage/ChildMainPage.tsx
  frontend/src/pages/ChildPage/ChildMenuPage/ChildMenuPage.tsx
  frontend/src/pages/ChildPage/ChildMissionPage/ChildMissionDetailPage.tsx
  frontend/src/pages/ChildPage/ChildMissionPage/ChildMissionPage.tsx
  frontend/src/pages/ChildPage/ChildRegisterPage/ChildRegisterPage.tsx
  frontend/src/pages/ChildPage/ChildTradePage/ChildTradeDetailPage.tsx
  frontend/src/pages/ChildPage/ChildTradePage/ChildTradePage.tsx
  frontend/src/pages/ChildPage/ChildWritePage/ChildWritePage.tsx
  frontend/src/pages/LoginPage/LoginPage.tsx
  frontend/src/pages/LoginPage/SignUpPage.tsx
  frontend/src/pages/ParentPage/ParentGiveMissionPage/ParentGiveMissionPage.tsx
  frontend/src/pages/ParentPage/ParentGiveMoneyPage/ParentGiveMoneyPage.tsx
  frontend/src/pages/ParentPage/ParentMainPage/ParentMainPage.tsx
  frontend/src/pages/ParentPage/ParentMenuPage/ParentMenuPage.tsx
  frontend/src/pages/ParentPage/ParentMissionPage/ParentMissionPage.tsx
  frontend/src/pages/ParentPage/ParentPatternPage/ParentPatternPage.tsx
  frontend/src/pages/ParentPage/ParentRegisterPage/ParentRegisterPage.tsx
  frontend/src/pages/ParentPage/ParentTradePage/ParentTradeDetailPage.tsx
  frontend/src/pages/ParentPage/ParentTradePage/ParentTradePage.tsx
  frontend/src/react-app-env.d.ts
  frontend/src/reportWebVitals.ts
  frontend/src/service-worker.ts
  frontend/src/serviceWorkerRegistration.ts
  frontend/src/setupTests.ts
  frontend/tsconfig.json
Labels: feat

#8 feat: add member domain entity (#7)
  backend/.gitignore
  backend/src/main/generated/com/shinhan/shbhack/ijoa/domain/member/QMember.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Family.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Friend.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Member.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Mission.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Notification.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/ProfileImage.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/enums/Accomplishment.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/enums/ActivateStatus.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/enums/ConfirmStatus.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/enums/Gender.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/enums/MemberRole.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/enums/NotificationType.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/jpa/FamilyRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/jpa/FriendRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/jpa/MemberRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/jpa/MissionRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/jpa/NotificationRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/jpa/ProfileImageRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/query/MemberQueryRepository.java
  backend/src/main/resources/application.yml
Labels: feat

#11 [FE] feat/init project
  frontend/src/App.tsx
Labels: feat

#15 feat: Dockerfile 추가 (#14)
  backend/Dockerfile
  frontend/Dockerfile
Labels: feat

#17 feat: Dockerfile 수정 (#16)
  backend/Dockerfile
Labels: feat

#18 feat: Dockerfile 수정 (#16)
  backend/Dockerfile
Labels: feat

#19 feat: Dockerfile 수정 (#16)
  backend/Dockerfile
Labels: feat

#23 Fe feat/child dairy
  frontend/src/App.tsx
  frontend/src/components/ChildDiary/DiaryCalendar.tsx
  frontend/src/components/ChildDiary/DiaryContent.tsx
  frontend/src/components/ChildDiary/DiaryContentStyles.tsx
  frontend/src/components/ChildMisson/ChildInfo.tsx
  frontend/src/components/ChildMisson/ChildInfoStyles.tsx
  frontend/src/components/ChildMisson/MissionList.tsx
  frontend/src/components/ChildMisson/MissionListItem.tsx
  frontend/src/components/ChildMisson/MissionListStyles.tsx
  frontend/src/pages/ChildPage/ChildDiaryPage/ChildDiaryPage.tsx
  frontend/src/pages/ChildPage/ChildMissionPage/ChildMissionDetailPage.tsx
  frontend/src/pages/ChildPage/ChildMissionPage/ChildMissionPage.tsx
  frontend/src/pages/ChildPage/ChildMissionPage/ChildMissionPageStyles.tsx
Labels: feat

#28 Be feat/member
  backend/src/main/generated/com/shinhan/shbhack/ijoa/domain/QBaseEntity.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/diary/dto/request/DiaryServiceRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/diary/dto/response/DiaryResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/request/MemberServiceRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/response/MemberResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/config/QueryDslConfig.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/config/SwaggerConfig.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/file/FileExtensionFilter.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/file/FileStore.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/file/UploadFile.java
Labels: feat

#33 feat: 부모메인페이지 (#32)
  frontend/src/components/ParentMain/GiveMissionButton.tsx
  frontend/src/components/ParentMain/GiveMissionButtonStyles.tsx
  frontend/src/components/ParentMain/GiveMoneyButton.tsx
  frontend/src/components/ParentMain/GiveMoneyButtonStyles.tsx
  frontend/src/components/ParentMain/MissionButton.tsx
  frontend/src/components/ParentMain/MissionButtonStyles.tsx
  frontend/src/components/ParentMain/ParentInfo.tsx
  frontend/src/components/ParentMain/ParentInfoStyles.tsx
  frontend/src/components/ParentMain/PatternButton.tsx
  frontend/src/components/ParentMain/PatternButtonStyles.tsx
  frontend/src/components/ParentMain/TradeListButton.tsx
  frontend/src/components/ParentMain/TradeListButtonStyles.tsx
  frontend/src/pages/ParentPage/ParentMainPage/ParentMainPage.tsx
Labels: feat

#41 Fe feat/common page
  frontend/src/components/Login/Login.tsx
  frontend/src/components/SignUp.tsx/ChildSignUp.tsx
  frontend/src/components/SignUp.tsx/ParentSignUp.tsx
  frontend/src/pages/LoginPage/LoginPage.tsx
  frontend/src/pages/LoginPage/SignUpPage.tsx
Labels: feat

#43 feat: add sample code(#42)
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/diary/DiaryController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/diary/requestdto/DiaryCreateRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/diary/requestdto/DiaryRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/MemberController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/requestdto/MemberCreateRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/diary/command/DiaryService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/diary/dto/request/DiaryCreateServiceRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/diary/dto/request/DiaryServiceRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/diary/dto/response/DiaryDetailResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/diary/dto/response/DiaryResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/diary/query/DiaryQueryService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/request/MemberCreateServiceRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/request/MemberServiceRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/response/MemberDetailResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/response/MemberResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/config/SecurityConfig.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/config/WebConfig.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/jwt/JwtUtils.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/repository/datajpa/CommentRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/repository/datajpa/DiaryImageRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/repository/datajpa/DiaryRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/repository/datajpa/DiaryShareRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/repository/jpa/DiaryRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/repository/query/DiaryQueryRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/datajpa/FamilyRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/datajpa/FriendRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/datajpa/MemberRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/datajpa/MissionRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/datajpa/NotificationRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/datajpa/ProfileImageRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/query/MemberQueryRepository.java
Labels: feat

#45 feat: add member domain relationship mapping (#44)
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Member.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Notification.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/ProfileImage.java
Labels: feat

#47 feat: diary JPA 작성(#31)
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/repository/jpa/DiaryRepository.java
Labels: feat

#48 feat: diary JPA 중복 삭제(#31)
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/repository/jpa/CommentRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/repository/jpa/DiaryImageRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/repository/jpa/DiaryRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/repository/jpa/DiaryShareRepository.java
Labels: feat

#49 Fe feat/parent give mission page
  frontend/package-lock.json
  frontend/package.json
  frontend/public/weather/drop.png
  frontend/public/weather/snowflake.png
  frontend/public/weather/sunny.png
  frontend/public/weather/sunrise.png
  frontend/public/weather/thunder.png
  frontend/public/weather/wind.png
  frontend/src/components/ChildMain/ChildInfo.tsx
  frontend/src/components/ChildWrite/DiaryCalender.tsx
  frontend/src/components/ChildWrite/MoodWeather.tsx
  frontend/src/components/ChildWrite/WriteDiary.tsx
  frontend/tailwindcss.d.tsx
  frontend/tsconfig.json
Labels: feat

#60 feat: security 관련 주석, baseEntity 어노테이션 추가, 작성 테스트 확인 및 리스트는 아직..
  backend/src/main/java/com/shinhan/shbhack/ijoa/IjoaApplication.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/diary/DiaryController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/diary/requestdto/DiaryCreateRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/diary/command/DiaryService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/diary/dto/request/DiaryCreateServiceRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/config/SecurityConfig.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/entity/Diary.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/entity/DiaryImage.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/repository/datajpa/DiaryRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/repository/query/DiaryQueryRepository.java
  backend/src/main/resources/application.yml
Labels: feat

#62 security 비활성화 & yml 파일 분할 (#61)
  backend/.gitignore
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/MemberController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/config/SecurityConfig.java
  backend/src/main/resources/application-db.yml
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-email.yml
  backend/src/main/resources/application-jwt.yml
  backend/src/main/resources/application-oauth.yml
  backend/src/main/resources/application-openapi.yml
  backend/src/main/resources/application-server.yml
  backend/src/main/resources/application.yml
Labels: feat

#63 Be feat/diary api
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/diary/DiaryController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/diary/command/DiaryService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/diary/dto/response/DiaryCalenderResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/diary/dto/response/DiaryDetailResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/diary/dto/response/DiaryImageResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/entity/Comment.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/entity/Diary.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/entity/DiaryImage.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/entity/DiaryShare.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/repository/datajpa/CommentRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/repository/query/DiaryQueryRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Member.java
Labels: feat

#64 Fe feat/child write diary page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ChildWrite/BottomButton.tsx
  frontend/src/components/ChildWrite/DiaryCalender.tsx
  frontend/src/components/ChildWrite/MoodWeather.tsx
  frontend/src/components/ChildWrite/TradeList.tsx
  frontend/src/components/ChildWrite/UploadPicture.tsx
  frontend/src/components/ChildWrite/VoiceRecord.tsx
  frontend/src/components/ChildWrite/WriteDiary.tsx
  frontend/src/pages/ChildPage/ChildWritePage/ChildWritePage.tsx
  frontend/src/store/DiaryStore.tsx
Labels: feat

#66 feat: 아이 메인페이지 (#65)
  frontend/src/asset/alarm.png
  frontend/src/asset/background/landing.gif
  frontend/src/asset/diary.png
  frontend/src/asset/home.png
  frontend/src/asset/menu.png
  frontend/src/asset/mission.png
  frontend/src/asset/trade.png
  frontend/src/asset/write.png
  frontend/src/components/ChildMain/ChildInfo.tsx
  frontend/src/components/ChildMain/ChildInfoStyles.tsx
  frontend/src/components/ChildMain/ChildMissionButton.tsx
  frontend/src/components/ChildMain/ChildMissionButtonStyles.tsx
  frontend/src/components/ChildMain/ReadDiaryButtonStyles.tsx
  frontend/src/components/ChildMain/ReadDirayButton.tsx
  frontend/src/components/ChildMain/TradeListButton.tsx
  frontend/src/components/ChildMain/TradeListButtonStyles.tsx
  frontend/src/components/ChildMain/WriteDiaryButton.tsx
  frontend/src/components/ChildMain/WriteDiaryButtonStyles.tsx
  frontend/src/components/Common/BottomNav.tsx
  frontend/src/components/Common/BottomNavStyles.tsx
  frontend/src/components/ParentGiveMoney/ParentGiveMoney.tsx
  frontend/src/components/ParentGiveMoney/ParentGiveMoneyStyles.tsx
  frontend/src/pages/ChildPage/ChildMainPage/ChildMainPage.tsx
  frontend/src/pages/ChildPage/ChildMainPage/ChildMainPageStyles.tsx
  frontend/src/pages/ParentPage/ParentGiveMissionPage/ParentGiveMissionPage.tsx
  frontend/src/pages/ParentPage/ParentGiveMoneyPage/ParentGinveMoneyStyles.tsx
  frontend/src/pages/ParentPage/ParentGiveMoneyPage/ParentGiveMoneyPage.tsx
Labels: feat

#68 feat: add, api response, error handler, security config (#67)
  backend/build.gradle
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/MemberController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/config/SecurityConfig.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/config/WebConfig.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/dto/response/ApiError.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/dto/response/ApiPage.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/dto/response/ApiResult.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/dto/response/ApiSingleData.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/error/ErrorCode.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/error/ExceptionControllerAdvice.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/error/exception/EntityNotFoundException.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/error/exception/InvalidValueException.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/error/exception/ServiceRuntimeException.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/jwt/AuthTokens.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/jwt/AuthTokensGenerator.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/jwt/JwtTokenProvider.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/jwt/JwtUtils.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/jwt/KakaoTokens.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/jwt/NaverTokens.java
  backend/src/main/resources/messages.properties
Labels: feat

#70 feat:secret key change and key mapping (#69)
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/jwt/JwtTokenProvider.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Member.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Notification.java
  backend/src/main/resources/application-jwt.yml
Labels: feat

#73 Fe feat/auth page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ChildMisson/MissionList.tsx
  frontend/src/components/ChildWrite/BottomButton.tsx
  frontend/src/components/ChildWrite/DiaryCalender.tsx
  frontend/src/components/ChildWrite/UploadPicture.tsx
  frontend/src/components/Common/BottomNav.tsx
  frontend/src/components/Login/Login.tsx
  frontend/src/components/SignUp.tsx/ChildSignUp.tsx
  frontend/src/index.tsx
  frontend/src/pages/ChildPage/ChildWritePage/ChildWritePage.tsx
  frontend/src/pages/LoginPage/SignUpPage.tsx
  frontend/src/store/UserStore.tsx
Labels: feat

#75 feat : 부모 페이지 메인 구성 (#74)
  frontend/src/App.tsx
  frontend/src/asset/givemoney.png
  frontend/src/components/Common/BottomNav.tsx
  frontend/src/components/ParentGiveMoney/ParentGiveMoney.tsx
  frontend/src/components/ParentGiveMoney/ParentGiveMoneyStyles.tsx
  frontend/src/components/ParentMain/GiveMissionButton.tsx
  frontend/src/components/ParentMain/GiveMissionButtonStyles.tsx
  frontend/src/components/ParentMain/GiveMoneyButton.tsx
  frontend/src/components/ParentMain/GiveMoneyButtonStyles.tsx
  frontend/src/components/ParentMain/MissionButton.tsx
  frontend/src/components/ParentMain/MissionButtonStyles.tsx
  frontend/src/components/ParentMain/ParentInfo.tsx
  frontend/src/components/ParentMain/ParentInfoStyles.tsx
  frontend/src/components/ParentMain/PatternButton.tsx
  frontend/src/components/ParentMain/PatternButtonStyles.tsx
  frontend/src/components/ParentMain/TradeListButton.tsx
  frontend/src/components/ParentMain/TradeListButtonStyles.tsx
  frontend/src/pages/CommonPage/AlarmPage.tsx
  frontend/src/pages/CommonPage/MenuPage.tsx
  frontend/src/pages/ParentPage/ParentMainPage/ParentMainPage.tsx
  frontend/src/pages/ParentPage/ParentMainPage/ParentMainPageStyles.tsx
Labels: feat

#77 feat: 아이페이지 전반적인 틀 구현하기(#76)
  frontend/src/components/ChildTrade/ChildTradeList.tsx
  frontend/src/components/ChildWrite/BottomButton.tsx
  frontend/src/components/ChildWrite/UploadPicture.tsx
  frontend/src/components/Login/Login.tsx
  frontend/src/pages/CommonPage/MenuPage.tsx
  frontend/src/store/DiaryStore.tsx
Labels: feat

#80 feat: 아이페이지 중 일기 읽기 기능 구현, 녹음 기능 테스트, 마이페이지 기본 틀 구현, 알람페이지 서식 지정, 뒤로 …
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/ChildDiary/DiaryCalendar.tsx
  frontend/src/components/ChildDiary/DiaryContent.tsx
  frontend/src/components/ChildWrite/VoiceRecord.tsx
  frontend/src/components/Common/BackPageButton.tsx
  frontend/src/components/Common/BottomNav.tsx
  frontend/src/components/Login/Login.tsx
  frontend/src/pages/ChildPage/ChildDiaryPage/ChildDiaryPage.tsx
  frontend/src/pages/ChildPage/ChildWritePage/ChildWritePage.tsx
  frontend/src/pages/CommonPage/AlarmPage.tsx
  frontend/src/pages/CommonPage/MyPage.tsx
  frontend/src/store/DiaryStore.tsx
Labels: feat

#81 fix : 다이어리 녹음, 이미지 수정
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/BankController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/requestdto/BankBalanceRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/requestdto/BankDepositRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/requestdto/BankTransactionRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/requestdto/BankTransferRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/diary/DiaryController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/diary/requestdto/DiaryCreateRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/command/BankService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankAccountResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankBalanceResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankDepositResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankTransactionResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankTransferResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/entity/Account.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/entity/Transaction.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/entity/TransactionCategory.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/datajpa/AccountRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/datajpa/TransactionCategoryRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/datajpa/TransactionRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/query/TransactionQueryRepository.java
Labels: feat

#82 fix : 다이어리 녹음, 이미지 수정
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/diary/command/DiaryService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/entity/Diary.java
Labels: feat

#84 Be feat/diary api
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/BankController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/requestdto/BankBalanceRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/requestdto/BankDepositRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/requestdto/BankTransactionRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/requestdto/BankTransferRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/diary/DiaryController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/diary/requestdto/DiaryCreateRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/command/BankService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankAccountResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankBalanceResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankDepositResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankTransactionResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankTransferResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/diary/command/DiaryService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/entity/Account.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/entity/Transaction.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/entity/TransactionCategory.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/datajpa/AccountRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/datajpa/TransactionCategoryRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/datajpa/TransactionRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/query/TransactionQueryRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/entity/Diary.java
Labels: feat

#86 feat: mapping entity
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/entity/DiaryShare.java
Labels: feat

#89 feat: Bank 거래내역조회, 잔액조회 구현
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/BankController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/command/BankService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankAccountResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankTransactionResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/DataInitializer.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/entity/Account.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/entity/Transaction.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/entity/TransactionCategory.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/query/TransactionQueryRepository.java
Labels: feat

#91 feat: 계좌이체 API 구현 (#90)
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/BankController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/dto/request/BankTransferRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/command/BankService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankTransferResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/DataInitializer.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/datajpa/AccountRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/datajpa/TransactionRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/query/TransactionQueryRepository.java
Labels: feat

#92 feat: 계좌이체 잔액 초과 예외 처리 (#90)
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/command/BankService.java
Labels: feat

#93 Fe feat/auth page
  frontend/src/components/ChildDiary/DiaryCalendar.module.css
  frontend/src/components/ChildDiary/DiaryCalendar.tsx
  frontend/src/components/ChildDiary/DiaryContent.tsx
  frontend/src/components/ChildTrade/ChildTradeList.tsx
  frontend/src/components/ChildWrite/BottomButton.tsx
  frontend/src/components/ChildWrite/MoodWeather.tsx
  frontend/src/components/ChildWrite/UploadPicture.tsx
  frontend/src/components/ChildWrite/VoiceRecord.tsx
  frontend/src/pages/ChildPage/ChildTradePage/ChildTradePage.tsx
  frontend/src/store/DiaryStore.tsx
Labels: feat

#98 feat: 카테고리 분석 데이터 API (#90)
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/BankController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/dto/request/BankAnalyzeRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/command/BankService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankAnalyzeListResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankAnalyzeResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankDepositResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/DataInitializer.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/query/TransactionQueryRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/entity/Diary.java
Labels: feat

#99 feat: 사진 표시 API 추가
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/diary/DiaryController.java
Labels: feat

#100 Fe feat/auth page
  frontend/src/App.tsx
  frontend/src/components/ChildWrite/Picture.tsx
  frontend/src/components/Login/EmailAuthCheck.tsx
  frontend/src/components/Login/EmailAuthSend.tsx
  frontend/src/components/Login/Login.tsx
  frontend/src/components/ParentTrade/ParentTradeList.tsx
  frontend/src/pages/LoginPage/EmailAuthPage.tsx
  frontend/src/pages/LoginPage/SignUpPage.tsx
  frontend/src/pages/ParentPage/ParentTradePage/ParentTradePage.tsx
  frontend/src/store/SignUpStore.tsx
Labels: feat

#101 feat: 카테고리 분석 결과 수정
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/dto/response/BankAnalyzeListResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/query/TransactionQueryRepository.java
Labels: feat

#102 feat: 카테고리 분석 결과 수정
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/query/TransactionQueryRepository.java
Labels: feat

#104 feat : add security filter & config
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/MemberController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/diary/command/DiaryService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/response/MemberTokenResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/query/EmailQueryService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/query/MemberQueryService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/config/RedisConfig.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/config/SecurityConfig.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/dto/response/ApiError.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/dto/response/ApiResult.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/error/ErrorCode.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/error/ExceptionControllerAdvice.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/error/exception/EntityNotFoundException.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/error/exception/InvalidValueException.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/error/exception/ServiceRuntimeException.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/filter/FileExtensionFilter.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/filter/InvalidTokenEntryPoint.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/model/JwtCreateModel.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/model/UserDetailsModel.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/DataInitializerUtil.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/FileUtil.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/JwtUtil.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/RedisUtil.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/redis/RedisUtil.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/UploadFile.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/entity/DiaryImage.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/entity/DiaryRecord.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/entity/DiaryShare.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Member.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/ProfileImage.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/query/MemberQueryRepository.java
Labels: feat

#105 feat: 1원 인증 구현
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/BankController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/dto/request/BankAuthRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/command/BankService.java
Labels: feat

#107 fix: security jwt filter error
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/MemberController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/dto/request/MemberCreateRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/command/MemberService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/request/MemberCreateServiceRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/response/MemberProfileResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/config/CorsConfig.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/config/SecurityConfig.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/filter/FileExtensionFilter.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/DataInitializerUtil.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/FileUtil.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/JwtUtil.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/RedisUtil.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Member.java
Labels: fix

#108 Fe feat/auth page
  frontend/src/components/ChildDiary/DiaryContent.tsx
  frontend/src/components/ChildDiary/DiaryPicture.tsx
  frontend/src/components/ChildWrite/BottomButton.tsx
  frontend/src/components/ChildWrite/UploadPicture.tsx
  frontend/src/components/ChildWrite/VoiceRecord.tsx
  frontend/src/components/Login/EmailAuthCheck.tsx
  frontend/src/pages/ChildPage/ChildWritePage/ChildWritePage.tsx
  frontend/src/pages/LoginPage/EmailAuthPage.tsx
  frontend/src/pages/LoginPage/SignUpPage.tsx
  frontend/src/store/DiaryStore.tsx
  frontend/src/store/SignUpStore.tsx
Labels: feat

#112 Fe feat/auth page
  frontend/src/components/Login/Login.tsx
  frontend/src/pages/CommonPage/MyPage.tsx
  frontend/src/pages/LoginPage/SignUpPage.tsx
  frontend/src/store/UserStore.tsx
Labels: feat

#114 feat: 알람서비스 구현
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/alarm/AlarmController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/alarm/dto/request/AlarmConfirmRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/BankController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/dto/request/BankOneDayTransactionRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/alarm/command/AlarmService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/alarm/dto/request/AlarmNotifyRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/alarm/dto/response/AlarmInfoResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/command/BankService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/DataInitializerUtil.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/query/TransactionQueryRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Mission.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Notification.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/enums/NotificationType.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/datajpa/MemberRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/query/AlarmQueryRepository.java
Labels: feat

#116 feat:아이 거래내역 조회, 일기쓰기에서 거래내역 조회(#111)
  frontend/src/components/ChildTrade/ChildTradeList.tsx
  frontend/src/components/ChildWrite/DiaryCalender.tsx
  frontend/src/components/ChildWrite/TradeList.tsx
  frontend/src/store/UserStore.tsx
Labels: feat

#117 fix: resolve cors error
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/DataInitializerUtil.java
Labels: fix

#118 Fe feat/auth page
  frontend/.prettierrc
  frontend/public/auth/authCheckEmail.gif
  frontend/public/auth/authSendEmail.gif
  frontend/public/auth/logo.gif
  frontend/public/auth/logo2.gif
  frontend/src/App.tsx
  frontend/src/components/ChildDiary/DiaryCalendar.tsx
  frontend/src/components/ChildDiary/DiaryContent.tsx
  frontend/src/components/ChildWrite/BottomButton.tsx
  frontend/src/components/ChildWrite/TradeList.tsx
  frontend/src/components/Common/BottomNav.tsx
  frontend/src/components/Login/EmailAuthCheck.tsx
  frontend/src/components/Login/EmailAuthSend.tsx
  frontend/src/components/Login/Login.tsx
  frontend/src/components/Login/LoginStyles.tsx
  frontend/src/pages/ChildPage/ChildWritePage/ChildWritePage.tsx
  frontend/src/pages/CommonPage/MyPage.tsx
  frontend/src/pages/LoginPage/EmailAuthPage.tsx
  frontend/src/pages/LoginPage/SignUpPage.tsx
Labels: feat

#119 feat : 부모페이지 axios기능 구현(#111)
  frontend/src/components/ChildMain/ChildInfo.tsx
  frontend/src/components/ChildMain/ChildInfoStyles.tsx
  frontend/src/components/ChildMain/ChildMissionButtonStyles.tsx
  frontend/src/components/ChildMain/ReadDiaryButtonStyles.tsx
  frontend/src/components/ChildMain/TradeListButtonStyles.tsx
  frontend/src/components/ChildMain/WriteDiaryButtonStyles.tsx
  frontend/src/components/Common/AccountRegisterStyles.tsx
  frontend/src/components/Common/AccountRegsiter.tsx
  frontend/src/components/Common/BottomNav.tsx
  frontend/src/components/ParentGiveMission/GiveMissionCalendar.tsx
  frontend/src/components/ParentGiveMission/GiveMissionDetail.tsx
  frontend/src/components/ParentGiveMission/GiveMissionDetailStyles.tsx
  frontend/src/components/ParentGiveMoney/ParentGiveMoney.tsx
  frontend/src/components/ParentMain/ParentInfo.tsx
  frontend/src/components/ParentPattern/PatternGraph.tsx
  frontend/src/components/ParentRegister/ParentRegister.tsx
  frontend/src/components/ParentRegister/ParentRegisterStyles.tsx
  frontend/src/pages/ChildPage/ChildMainPage/ChildMainPage.tsx
  frontend/src/pages/CommonPage/AccountRegisterPage.tsx
  frontend/src/pages/ParentPage/ParentMainPage/ParentMainPage.tsx
  frontend/src/pages/ParentPage/ParentRegisterPage/ParentRegisterPage.tsx
  frontend/src/pages/ParentPage/ParentRegisterPage/ParentRegisterPageStyles.tsx
  frontend/src/store/UserStore.tsx
Labels: feat

#120 Fe feat/auth page
  frontend/src/components/Login/EmailAuthCheck.tsx
  frontend/src/components/Login/EmailAuthSend.tsx
  frontend/src/pages/ChildPage/ChildMainPage/ChildMainPage.tsx
  frontend/src/pages/ChildPage/ChildMainPage/ChildMainPageStyles.tsx
  frontend/src/pages/CommonPage/MyPage.tsx
Labels: feat

#122 Fe feat/parent main page
  frontend/src/components/ParentGiveMission/GiveMissionDetail.tsx
  frontend/src/components/ParentGiveMoney/ParentGiveMoney.tsx
  frontend/src/components/ParentMain/ParentInfo.tsx
  frontend/src/components/ParentPattern/PatternGraph.tsx
  frontend/src/components/ParentRegister/ParentRegister.tsx
  frontend/src/components/ParentTrade/ParentTradeList.tsx
  frontend/src/pages/ChildPage/ChildMainPage/ChildMainPage.tsx
  frontend/src/pages/ParentPage/ParentMainPage/ParentMainPage.tsx
Labels: feat

#123 [FE]알람 조회 기능 구현, 삭제 기능 구현
  frontend/public/illustration_404.svg
  frontend/src/App.tsx
  frontend/src/components/ChildWrite/TradeList.tsx
  frontend/src/components/Login/Login.tsx
  frontend/src/components/Login/LoginStyles.tsx
  frontend/src/components/ParentTrade/ParentTradeList.tsx
  frontend/src/pages/ChildPage/ChildMainPage/ChildMainPage.tsx
  frontend/src/pages/CommonPage/AlarmPage.tsx
  frontend/src/pages/CommonPage/Page404.tsx
Labels: feat

#125 feat:페이지 글씨체 수정, 다이어리 읽기 스타일 수정, 회원가입 스타일 수정, 아이 일기 쓰기 스타일 수정(#124)
  frontend/public/diary/noImage.png
  frontend/src/components/ChildDiary/DiaryCalendar.tsx
  frontend/src/components/ChildDiary/DiaryContent.tsx
  frontend/src/components/ChildTrade/ChildTradeList.tsx
  frontend/src/components/ChildWrite/BottomButton.tsx
  frontend/src/components/ChildWrite/DiaryCalender.tsx
  frontend/src/components/ChildWrite/MoodWeather.tsx
  frontend/src/components/Common/AccountRegisterStyles.tsx
  frontend/src/components/Common/AccountRegsiter.tsx
  frontend/src/components/Login/EmailAuthCheck.tsx
  frontend/src/components/Login/EmailAuthSend.tsx
  frontend/src/components/Login/Login.tsx
  frontend/src/components/Login/LoginStyles.tsx
  frontend/src/pages/ChildPage/ChildWritePage/ChildWritePage.tsx
  frontend/src/pages/CommonPage/AccountRegisterPage.tsx
  frontend/src/pages/CommonPage/MyPage.tsx
  frontend/src/pages/LoginPage/SignUpPage.tsx
  frontend/src/store/DiaryStore.tsx
Labels: feat

#128 feat: 전체적인 글씨체 변경, 아이콘 추가, 마이페이지에서 프로필 사진 변경 기능 추가
  frontend/src/components/ChildDiary/DiaryCalendar.tsx
  frontend/src/components/ChildDiary/DiaryContent.tsx
  frontend/src/components/ChildTrade/ChildTradeList.tsx
  frontend/src/components/ChildWrite/BottomButton.tsx
  frontend/src/components/Common/AccountRegsiter.tsx
  frontend/src/components/Common/BottomNav.tsx
  frontend/src/components/ParentRegister/ParentRegister.tsx
  frontend/src/components/ParentRegister/ParentRegisterStyles.tsx
  frontend/src/pages/CommonPage/AlarmPage.tsx
  frontend/src/pages/CommonPage/MyPage.tsx
Labels: feat

#130 feat: add member api
  backend/.gitignore
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/AuthController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/EmailController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/MemberController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/MissionController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/query/MemberQueryService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/config/CorsConfig.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/error/ExceptionControllerAdvice.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/filter/InvalidTokenEntryPoint.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/model/JwtCreateModel.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/response/ApiData.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/response/ApiError.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/response/ApiPage.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/response/ApiResult.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/DataInitializerUtil.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/JwtUtil.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Member.java
Labels: feat

#131 fix version compatible
  backend/build.gradle
Labels: feat, fix

#133 feat:용돈일기 읽을 때 거래내역 불러오는 기능 구현, 알람페이지와 거래내역 카테고리에 따른 아이콘 수정, 다이어리 캘린더…
  frontend/package-lock.json
  frontend/package.json
  frontend/public/alarm/CHILD_ENROLL.png
  frontend/public/alarm/CHILD_MISSION.png
  frontend/public/alarm/PARENT_MISSION.png
  frontend/public/alarm/WITHDRAWL.png
  frontend/public/trade/1.png
  frontend/public/trade/2.png
  frontend/public/trade/3.png
  frontend/public/trade/4.png
  frontend/public/trade/5.png
  frontend/public/trade/6.png
  frontend/public/trade/7.png
  frontend/public/trade/8.png
  frontend/src/App.tsx
  frontend/src/components/ChildDiary/DiaryCalendar.tsx
  frontend/src/components/ChildDiary/DiaryCalendar2.tsx
  frontend/src/components/ChildDiary/DiaryContent.tsx
  frontend/src/components/ChildTrade/ChildTradeList.tsx
  frontend/src/components/ChildWrite/TradeList.tsx
  frontend/src/components/Common/BottomNav.tsx
  frontend/src/components/Login/EmailAuthSend.tsx
  frontend/src/pages/ChildPage/ChildDiaryPage/ChildDiaryPage.tsx
  frontend/src/pages/CommonPage/AlarmPage.tsx
Labels: feat

#136 fix: fix redis connection error
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/config/RedisConfig.java
Labels: fix

#137 feat: 용돈 일기 작성한 날에만 달력 선택할 수 있는 기능 구현
  frontend/package.json
  frontend/src/components/ChildDiary/DiaryCalendar.tsx
Labels: feat

#139 fix: email send error
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/EmailController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/MemberController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/dto/request/EmailCheckRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/dto/request/MemberCreateRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/dto/request/MemberLoginRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/request/EmailCheckServiceRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/request/MemberCreateServiceRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/request/MemberLoginServiceRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/query/EmailQueryService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/query/MemberQueryService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/config/CorsConfig.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/error/ErrorCode.java
Labels: fix

#140 feat: regist child
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/EmailController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/FamilyController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/MemberController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/dto/request/MemberRegistFamilyRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/command/FamilyService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/command/MemberService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/request/MemberRegistFamilyServiceRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/query/FamilyQueryService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/query/MissionQueryService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/error/ErrorCode.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/datajpa/MemberRepository.java
  backend/src/main/resources/application-server.yml
Labels: feat

#141 refactor: 미션 상태 한글수정
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/enums/Accomplishment.java
Labels: refactor

#143 feat: 미션 리스트 기능 추가
  backend/.gitignore
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/MissionController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/dto/request/MissionListRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/command/MemberService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/request/MissionListServiceRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/response/MissionListResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/response/MissionSummaryResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/query/MissionQueryService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/error/ErrorCode.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/query/MissionQueryRepository.java
Labels: feat

#145 feat: axios 정리 & 예외처리
  frontend/src/components/ChildMain/ChildInfo.tsx
  frontend/src/components/ChildMisson/MissionListItemStyles.tsx
  frontend/src/components/ChildMisson/MissionRequestItem.tsx
  frontend/src/components/ChildRegister/ChildRegisterItemStyles.tsx
  frontend/src/components/Common/BottomNav.tsx
  frontend/src/components/ParentGiveMission/GiveMissionDetail.tsx
  frontend/src/components/ParentGiveMoney/ParentGiveMoney.tsx
  frontend/src/components/ParentMain/GiveMissionButton.tsx
  frontend/src/components/ParentMain/ParentInfo.tsx
  frontend/src/components/ParentMission/MissionList.tsx
  frontend/src/components/ParentMission/MissionListItem.tsx
  frontend/src/components/ParentMission/MissionListItemStyles.tsx
  frontend/src/components/ParentPattern/PatternGraph.tsx
  frontend/src/components/ParentRegister/ParentRegister.tsx
  frontend/src/pages/ChildPage/ChildMainPage/ChildMainPage.tsx
  frontend/src/pages/ParentPage/ParentMainPage/ParentMainPage.tsx
  frontend/src/pages/ParentPage/ParentMissionPage/ParentMissionDetailPage.tsx
Labels: feat

#147 fix: search member error
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/MissionController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/dto/request/MissionCreateRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/command/MissionService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/request/MissionCreateServiceRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/response/AccountResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/response/MemberParentHomeResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/dto/response/ProfileImageResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Mission.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Notification.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/enums/NotificationType.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/query/MissionQueryRepository.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-server.yml
Labels: fix

#148 feat : 계좌등록 관련 예외 처리
  frontend/src/components/ChildMain/ChildInfo.tsx
  frontend/src/components/ChildMain/ChildMissionButton.tsx
  frontend/src/components/ChildMain/ReadDirayButton.tsx
  frontend/src/components/ChildMain/TradeListButton.tsx
  frontend/src/components/ChildMain/WriteDiaryButton.tsx
  frontend/src/components/ChildMisson/MissionCompleteItem.tsx
  frontend/src/components/ChildMisson/MissionList.tsx
  frontend/src/components/ChildMisson/MissionListItem.tsx
  frontend/src/components/ChildMisson/MissionRequestItem.tsx
  frontend/src/components/Common/AccountRegsiter.tsx
  frontend/src/components/Common/BottomNav.tsx
  frontend/src/components/ParentGiveMission/GiveMissionDetail.tsx
  frontend/src/components/ParentGiveMoney/ParentGiveMoney.tsx
  frontend/src/components/ParentMain/GiveMissionButton.tsx
  frontend/src/components/ParentMain/GiveMoneyButton.tsx
  frontend/src/components/ParentMain/MissionButton.tsx
  frontend/src/components/ParentMain/ParentInfo.tsx
  frontend/src/components/ParentMain/PatternButton.tsx
  frontend/src/components/ParentMain/TradeListButton.tsx
  frontend/src/components/ParentMission/MissionCompleteItem.tsx
  frontend/src/components/ParentMission/MissionList.tsx
  frontend/src/components/ParentMission/MissionListItem.tsx
  frontend/src/components/ParentMission/MissionRequestMission.tsx
  frontend/src/pages/ChildPage/ChildMainPage/ChildMainPage.tsx
  frontend/src/pages/ChildPage/ChildMissionPage/ChildMissionDetailPage.tsx
  frontend/src/pages/ChildPage/ChildMissionPage/ChildMissionDetailPageStyles.tsx
  frontend/src/pages/CommonPage/AlarmPage.tsx
  frontend/src/pages/LoginPage/EmailAuthPage.tsx
  frontend/src/pages/LoginPage/SignUpPage.tsx
  frontend/src/pages/ParentPage/ParentMainPage/ParentMainPage.tsx
  frontend/src/pages/ParentPage/ParentMissionPage/ParentMissionDetailPage.tsx
  frontend/src/pages/ParentPage/ParentMissionPage/ParentMissionDetailPageStyles.tsx
Labels: feat

#149 feat: 달력 디자인 적용, 거래내역 조회에 BottomNav 추가
  frontend/src/App.tsx
  frontend/src/components/ChildDiary/CustomDatePicker.css
  frontend/src/components/ChildDiary/DiaryCalendar.tsx
  frontend/src/components/ChildTrade/ChildTradeList.tsx
  frontend/src/components/ChildWrite/Picture.tsx
  frontend/src/components/ChildWrite/TradeList.tsx
  frontend/src/components/ChildWrite/VoiceRecord.tsx
  frontend/src/components/ParentTrade/ParentTradeList.tsx
  frontend/src/pages/ChildPage/ChildWritePage/ChildWritePage.tsx
Labels: feat

#150 feat: create mission
  backend/.gitignore
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/MissionController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/command/MissionService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/entity/Account.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Mission.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Notification.java
Labels: feat

#151 feat: 유저의 계좌 등록 로직 수정
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/bank/dto/request/BankAuthRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/command/BankService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Member.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/datajpa/EmitterRepository.java
Labels: feat

#152 feat: 유저의 계좌 등록 로직 수정
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/entity/Account.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Member.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/datajpa/EmitterRepository.java
Labels: feat

#153 feat: SSE 알림 구현
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/alarm/AlarmController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/alarm/command/AlarmService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Member.java
Labels: feat

#154 feat: SSE 알람 기능 구현
  frontend/src/components/ChildMain/ChildInfo.tsx
  frontend/src/components/ChildTrade/ChildTradeList.tsx
  frontend/src/components/Common/BottomNav.tsx
  frontend/src/components/Login/Login.tsx
  frontend/src/components/ParentMain/ParentInfo.tsx
  frontend/src/components/ParentTrade/ParentTradeList.tsx
  frontend/src/pages/ChildPage/ChildMainPage/ChildMainPage.tsx
  frontend/src/pages/CommonPage/MyPage.tsx
  frontend/src/pages/ParentPage/ParentMainPage/ParentMainPage.tsx
Labels: feat

#156 feat: 회원가입 예외처리
  frontend/src/components/ChildTrade/ChildTradeList.tsx
  frontend/src/components/Common/AccountRegsiter.tsx
  frontend/src/components/ParentGiveMission/GiveMissionDetail.tsx
  frontend/src/components/ParentRegister/ParentRegister.tsx
  frontend/src/components/ParentTrade/ParentTradeList.tsx
  frontend/src/pages/CommonPage/AlarmPage.tsx
  frontend/src/pages/LoginPage/SignUpPage.tsx
Labels: feat

#157 feat: SSE 알람 기능 구현
  frontend/src/components/Common/BottomNav.tsx
  frontend/src/store/UserStore.tsx
Labels: feat

#160 Fe feat/parent main page
  frontend/src/components/ChildMisson/MissionListItem.tsx
  frontend/src/components/ChildTrade/ChildTradeList.tsx
  frontend/src/components/Common/AccountRegsiter.tsx
  frontend/src/components/ParentRegister/ParentRegisterStyles.tsx
  frontend/src/components/ParentTrade/ParentTradeList.tsx
  frontend/src/pages/CommonPage/MyPage.tsx
Labels: feat

#161 Fe feat/auth page
  frontend/src/components/ChildDiary/CustomDatePicker.css
  frontend/src/components/ChildDiary/DiaryCalendar.tsx
  frontend/src/components/ChildMain/ChildInfo.tsx
  frontend/src/components/ChildMain/WriteDiaryButton.tsx
  frontend/src/components/ChildTrade/ChildTradeList.tsx
  frontend/src/components/ParentGiveMission/GiveMissionDetail.tsx
  frontend/src/components/ParentGiveMoney/ParentGiveMoney.tsx
  frontend/src/components/ParentMain/ParentInfo.tsx
  frontend/src/components/ParentMission/MissionList.tsx
  frontend/src/components/ParentPattern/PatternGraph.tsx
  frontend/src/components/ParentTrade/ParentTradeList.tsx
Labels: feat

#163 fix: 이체가 안되는 문제 수정
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/command/BankService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/entity/Account.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/datajpa/MemberRepository.java
Labels: feat

#165 refactor : 불필요한 주석 제거
  frontend/src/App.tsx
  frontend/src/components/ChildDiary/DiaryCalendar.tsx
  frontend/src/components/ChildWrite/UploadPicture.tsx
  frontend/src/components/ChildWrite/WriteDiary.tsx
  frontend/src/components/Common/BottomNav.tsx
  frontend/src/pages/ChildPage/ChildDiaryPage/ChildDiaryPage.tsx
  frontend/src/pages/ChildPage/ChildMenuPage/ChildMenuPage.tsx
  frontend/src/pages/ChildPage/ChildTradePage/ChildTradeDetailPage.tsx
  frontend/src/pages/LoginPage/SignUpPage.tsx
  frontend/src/pages/ParentPage/ParentMenuPage/ParentMenuPage.tsx
  frontend/src/pages/ParentPage/ParentTradePage/ParentTradeDetailPage.tsx
Labels: feat, refactor

#166 refactor : 불필요한 주석제거
  frontend/src/components/ParentMission/MissionRequestMission.tsx
  frontend/src/pages/CommonPage/AlarmPage.tsx
  frontend/src/pages/LoginPage/SignUpPage.tsx
  frontend/src/pages/ParentPage/ParentMainPage/ParentMainPage.tsx
Labels: feat

#168 fix: email send error fix
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/query/EmailQueryService.java
Labels: fix

#169 feat: 거래내역 카테고리에 따른 아이콘 다르게 띄우는 기능구현
  frontend/src/components/ChildTrade/ChildTradeList.tsx
  frontend/src/components/Common/BottomNav.tsx
  frontend/src/components/ParentTrade/ParentTradeList.tsx
  frontend/src/pages/ChildPage/ChildMainPage/ChildMainPage.tsx
  frontend/src/pages/ParentPage/ParentMainPage/ParentMainPage.tsx
Labels: feat

#170 fix : 서버의 시간이 안맞는 문제 디버깅
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/command/BankService.java
Labels: feat

#171 feat : restart jwt token filter
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/MemberController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/config/SecurityConfig.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/filter/JwtAuthenticationFilter.java
Labels: feat

#173 feat: 헤더에 accessToken담기 (JWT 기능 구현)
  frontend/src/components/ChildTrade/ChildTradeList.tsx
  frontend/src/components/ChildWrite/BottomButton.tsx
  frontend/src/pages/ChildPage/ChildMissionPage/ChildMissionDetailPage.tsx
  frontend/src/pages/CommonPage/MyPage.tsx
  frontend/src/pages/ParentPage/ParentMissionPage/ParentMissionDetailPage.tsx
Labels: feat

#174 Fe feat/parent main page
  frontend/src/components/ChildMisson/MissionListItem.tsx
  frontend/src/components/ChildTrade/ChildTradeList.tsx
  frontend/src/components/Login/Login.tsx
  frontend/src/components/ParentMission/MissionRequestMission.tsx
  package-lock.json
Labels: feat

#175 feat : 이미지 업로드 수정, 알림 읽음 처리 안되는 문제 수정
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/alarm/AlarmController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/diary/DiaryController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/alarm/command/AlarmService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/alarm/command/SSEService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/command/BankService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/diary/command/DiaryService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/bank/repository/datajpa/AccountRepository.java
Labels: feat

#177 refactor: 기능 재점검
  frontend/src/components/ChildMisson/MissionList.tsx
  frontend/src/components/ChildMisson/MissionListItem.tsx
  frontend/src/components/Common/BottomNav.tsx
  frontend/src/components/Login/Login.tsx
Labels: feat

#178 feat: 부모가 완료버튼 눌렀을때 아이에게 송금되는 기능 구현, 아이에게 용돈주는 기능 구현, 미션 리스트 기능 동작 확인
  frontend/public/alarm/REGIST_MISSION.png
  frontend/src/components/ChildDiary/DiaryContent.tsx
  frontend/src/components/ChildWrite/BottomButton.tsx
  frontend/src/components/ParentGiveMission/GiveMissionDetail.tsx
  frontend/src/components/ParentGiveMoney/ParentGiveMoney.tsx
  frontend/src/components/ParentMission/MissionList.tsx
  frontend/src/components/ParentMission/MissionRequestMission.tsx
  frontend/src/pages/CommonPage/AlarmPage.tsx
  frontend/src/pages/ParentPage/ParentMainPage/ParentMainPage.tsx
Labels: feat

#179 fix: 한 날짜에 여러 일기를 쓸 수 없게 수정
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/diary/command/DiaryService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/entity/Diary.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/repository/datajpa/DiaryRepository.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/repository/query/DiaryQueryRepository.java
Labels: feat

#180 Be feat/member
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/config/SecurityConfig.java
Labels: feat

#181 fix: 사진 필터 해제, 기본 프로필 설정
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/diary/DiaryController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/command/MemberService.java
Labels: feat

#182 fix: 사진 필터 해제, 기본 프로필 설정
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/config/SecurityConfig.java
Labels: feat

#183 fix: 사진 필터 해제, 기본 프로필 설정
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/command/MemberService.java
Labels: fix

#184 fix: 사진 필터 해제, 기본 프로필 설정
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/diary/dto/response/DiaryDetailResponse.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/command/MemberService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/repository/query/DiaryQueryRepository.java
Labels: fix

#185 feat: add logout
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/MemberController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/command/MissionService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/query/EmailQueryService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/query/MemberQueryService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/JwtUtil.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/common/util/RedisUtil.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/query/MemberQueryRepository.java
Labels: feat

#186 feat: SSE 알림 기능 구현, Axios 통신 과정 중 발생한 에러 해결
  frontend/src/components/ChildRegister/ChildRegister.tsx
  frontend/src/components/ChildWrite/DiaryCalender.tsx
  frontend/src/components/Common/BottomNav.tsx
  frontend/src/components/ParentTrade/ParentTradeList.tsx
  frontend/src/pages/ChildPage/ChildMissionPage/ChildMissionDetailPageStyles.tsx
  frontend/src/pages/LoginPage/EmailAuthPage.tsx
  frontend/src/pages/LoginPage/SignUpPage.tsx
  frontend/src/pages/ParentPage/ParentMissionPage/ParentMissionDetailPage.tsx
  frontend/src/pages/ParentPage/ParentMissionPage/ParentMissionDetailPageStyles.tsx
Labels: feat

#188 fix: 사진 필터 해제, 기본 프로필 설정
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/alarm/command/AlarmService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/diary/repository/datajpa/DiaryRepository.java
Labels: fix

#189 fix: SSE 테스트 빌드
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/alarm/command/AlarmService.java
Labels: feat

#193 fix: test token
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/TestController.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/controller/member/EmailController.java
Labels: feat

#194 refactor: 페이지 예외처리 및 리펙토링
  frontend/src/App.tsx
  frontend/src/components/Common/BottomNav.tsx
  frontend/src/pages/ChildPage/ChildMainPage/ChildMainPage.tsx
  frontend/src/pages/ChildPage/ChildWritePage/ChildWritePage.tsx
  frontend/src/pages/CommonPage/AccountRegisterPage.tsx
  frontend/src/pages/CommonPage/AlarmPage.tsx
  frontend/src/pages/CommonPage/MenuPage.tsx
  frontend/src/pages/CommonPage/MyPage.tsx
  frontend/src/pages/CommonPage/ShareDiaryPage.tsx
  frontend/src/pages/LoginPage/EmailAuthPage.tsx
  frontend/src/pages/LoginPage/SignUpPage.tsx
  frontend/src/pages/ParentPage/ParentGiveMoneyPage/ParentGiveMoneyPage.tsx
  frontend/src/pages/ParentPage/ParentMainPage/ParentMainPage.tsx
Labels: refactor

#195 refactor: 아이페이지, 아이 컴포넌트, 부모 컴포넌트 불필요한 코드 제거와 불필요한 주석 제거
  frontend/src/App.tsx
  frontend/src/components/ChildDiary/DiaryCalendar.tsx
  frontend/src/components/ChildDiary/DiaryCalendar2.tsx
  frontend/src/components/ChildDiary/DiaryContent.tsx
  frontend/src/components/ChildDiary/DiaryPicture.tsx
  frontend/src/components/ChildMain/ChildMissionButton.tsx
  frontend/src/components/ChildMain/WriteDiaryButton.tsx
  frontend/src/components/ChildMisson/MissionList.tsx
  frontend/src/components/ChildRegister/ChildRegister.tsx
  frontend/src/components/ChildRegister/ChildRegisterItem.tsx
  frontend/src/components/ChildRegister/ChildRegisterItemStyles.tsx
  frontend/src/components/ChildRegister/ChildRegisterStyles.tsx
  frontend/src/components/ChildTrade/ChildTradeList.tsx
  frontend/src/components/ChildWrite/BottomButton.tsx
  frontend/src/components/ChildWrite/DiaryCalender.tsx
  frontend/src/components/ChildWrite/MoodWeather.tsx
  frontend/src/components/ChildWrite/TradeList.tsx
  frontend/src/components/ChildWrite/UploadPicture.tsx
  frontend/src/components/ChildWrite/VoiceRecord.tsx
  frontend/src/components/Common/AccountRegsiter.tsx
  frontend/src/components/Login/EmailAuthCheck.tsx
  frontend/src/components/Login/EmailAuthSend.tsx
  frontend/src/components/Login/Login.tsx
  frontend/src/components/Login/LoginStyles.tsx
  frontend/src/components/ParentGiveMoney/ParentGiveMoney.tsx
  frontend/src/components/ParentMission/MissionList.tsx
  frontend/src/components/ParentMission/MissionRequestMission.tsx
  frontend/src/components/ParentPattern/PatternGraph.tsx
  frontend/src/components/ParentTrade/ParentTradeList.tsx
  frontend/src/components/SignUp.tsx/ChildSignUp.tsx
  frontend/src/components/SignUp.tsx/ParentSignUp.tsx
  frontend/src/pages/ChildPage/ChildMissionPage/ChildMissionDetailPage.tsx
  frontend/src/pages/ChildPage/ChildRegisterPage/ChildRegisterPage.tsx
  frontend/src/pages/ChildPage/ChildRegisterPage/ChildRegisterPageStyles.tsx
  frontend/src/store/DiaryStore.tsx
  frontend/tsconfig.json
Labels: refactor

#196 feat:라우터 기능 추가
  frontend/src/App.tsx
Labels: feat

#197 feat: mission request alarm
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/alarm/dto/request/AlarmNotifyRequest.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/member/command/MissionService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/enums/NotificationType.java
Labels: feat

#198 fix : 등록된 계좌인지 확인하는 부분 문제
  backend/src/main/java/com/shinhan/shbhack/ijoa/api/service/bank/command/BankService.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/repository/datajpa/MemberRepository.java
Labels: fix

#199 fix: mission send error
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Mission.java
  backend/src/main/java/com/shinhan/shbhack/ijoa/domain/member/entity/Notification.java
Labels: fix

#201 feat:마지막 사진 기능 구현
  frontend/public/alarm/CHECK_MISSION.png
Labels: feat

#203 docs: update readme.md
  README.md
Labels: docs
